### ISSUE TITLE
[Suggestion] Tooltip alignment

### ISSUE THREAD

**Issue by akater** [Sodel-the-Vociferous/helm-company#11]
company has got `company-tooltip-align-annotations` custom variable. Would be nice for it to trigger annotations alignment in helm-company buffers as well.

**Comment by Sodel-the-Vociferous** [comment]
That's a neat idea. Do you think it'd make sense to align them to the emacs `fill-column`?

**Comment by akater** [comment]
I suspect tooltips better not be placed too far from candidates themselves, so my initial approach would be to calculate the alignment based on the current candidates list, and use max length + 2 or 3 spaces. However, my knowledge of helm internals is negligible, and this could be too much hassle, namely too slow to redisplay smoothly, or too difficult to implement.

`helm-buffers-list` deals well with multiple columns. I looked into it for inspiration but did not get far yet.

**Comment by Sodel-the-Vociferous** [comment]
Hi @akater,

I feel bad about leaving this unimplemented, with an open issue, for so long. Unfortunately, this is not a feature that I will have time to develop myself.

For now, I am going to close this issue. Sorry, and best regards!
