### ISSUE TITLE
slme-company-after-completion sometimes fails to do its job when helm-company is used

### ISSUE THREAD

**Issue by akater** [Sodel-the-Vociferous/helm-company#12]
company backends can have post-completion hooks. According to the `company-backends` docstring,
> `post-completion': Called after a completion candidate has been inserted
into the buffer.

which means it should be called when helm-company was used for completion as well.

At the moment, at least one backend's (slime-company) post-completion hook won't activate if the completion was performed with helm-company. That's the only one I tested.

I'm not sure if this is an internal issue of helm-company. However, from what I saw, post-completion hook is only called in `company-cancel` which in turn is called in `company-finish` immediately after insertion. There is the following comment in the definition of `helm-company`:
```lisp
    ;; (company-call-frontends 'hide) Work around a quirk with company.
    ;; `company-complete' inserts the common part of all candidates into the
    ;; buffer. But, it doesn't update `company-prefix' -- and `company-prefix'
    ;; is all `company-finish' replaces in the buffer. (issue #9)
```
It looks like `helm-company` avoids calling `company-finish` and thus skips `company-cancel` (? — weird name) which would call backend-specific post-completion hook.

The same or something similar might apply to `company-completion-finished-hook` which is global (not backend-specific) but I haven't checked.

**Comment by Sodel-the-Vociferous** [comment]
Hi! Helm-company does call `company-finish`. `company-finish` is actually how the completion candidate gets inserted into the buffer, in the `helm-company-action-insert` function. So it's very strange that the hook is not being called.

The code under the comment you pointed out won't stop company-finish from running. That code just updates the `company-prefix` if company automatically inserts the common part of all available candidates.

I will try to test completion with slime-company this week if I get the chance.

**Comment by akater** [comment]
I was wrong, post-completion hook does get called.

However, there is still an issue. slime-company does not complete the symbol name automatically after it completes the package name. So the maintainer of slime-company had suggested a workaround https://github.com/anwyn/slime-company/issues/16#issuecomment-362537360 : `(setq slime-company-after-completion 'my/special-completion)` where `my/special-completion` triggers completion again when the last character is `:`. This function does get called after helm-company completion, and yet, no further completion is triggered.

**Comment by akater** [comment]
Sorry I've sent the previous comment unfinished accidetnally.

I admit, this is not a big deal since helm is good at suggesting symbols right up front. But this is an unexpected behaviour still, and it could lead to other potential issues. Besides, restricting the search to symbols in a specific package while picking the package itself first is not very unreasonable.

Just in case, Emacs in question is 26.0.91.

**Comment by Sodel-the-Vociferous** [comment]
That function does not appear to explicitly trigger completion again. If the company menu does show itself again, that would be company's auto-completion menu popping up.

Helm-company isn't an *auto*-complete interface. It only runs when you explicitly call the `helm-company` function. If anything, opening a second time when you only called the function once would be the unexpected behaviour.

To make sure `helm-company` gets called a second time, you will have to make sure it is called again from somwehere, like `my/special-completion`.

If you like, I can add a `helm-company-after-completion-hook`, where you can add a hook function like the one above, to call `helm-company` again. Would that work for you?

**Comment by akater** [comment]
Yes, I get it now. It would work but I'd rather avoid useless bloat in helm-company. Please add the hook only if you don't consider it as such.

**Comment by Sodel-the-Vociferous** [comment]
Done. Enjoy! :)

**Comment by Sodel-the-Vociferous** [comment]
(Just add your hook function to `helm-company-after-completion=hooks`.)

**Comment by akater** [comment]
Everything works as desired, thank you!

For posterity: one cannot use exactly the same function as linked. You
have to explicitly call `(company-completion)`.
