### ISSUE TITLE
is it possible to define helm-company as the default completion method?

### ISSUE THREAD

**Issue by vxe** [Sodel-the-Vociferous/helm-company#14]
aka no more menus, only helm list for whenever company is invoked?

**Comment by Sodel-the-Vociferous** [comment]
I looked into this a while ago. Helm-Company is not coded in the same way that Company's "official" frontends are. I'm sure it would be possible to refactor Helm-Company into a proper Company frontend, but it'd take a huge effort.

**Comment by cyruseuros** [comment]
@Sodel-the-Vociferous is probably right. That being said, I'm a lazy fuck, and this works:

```elisp
(use-package company
  :config (setq company-frontends nil)
  :hook (after-init . global-company-mode))
(use-package helm-company
  :general (general-def
             :keymaps '(company-mode-map company-active-map)
             "<tab>" #'helm-company
             "TAB" #'helm-company))
```

**Comment by Sodel-the-Vociferous** [comment]
See #17 if needed, but `helm-company` can directly be bound to <Tab>, or any other key. Please comment if `helm-company` needs to be improved for interactive use.
