### ISSUE TITLE
Command that may as well be bound to tab

### ISSUE THREAD

**Issue by cyruseuros** [Sodel-the-Vociferous/helm-company#17]
For those that want to use helm as a default completion method, I improved on the answer I posted  [here](https://github.com/Sodel-the-Vociferous/helm-company/issues/14), and this is straight up ready to bind to tab. Thoughts on adding something like this to the package? I've been using it for a few hours now with lsp and other backends such as elpy with absolutely no issues.

```elisp
(defun helm-company-complete ()
            (interactive)
            (when (company-complete) (helm-company)))
```

**Comment by Sodel-the-Vociferous** [comment]
I tried this for a few minutes. It works, but it seems to work exactly the same as using `helm-company` directly. Am I missing something?
