### ISSUE TITLE
Fill in the partially completed phrase in helm buffer

### ISSUE THREAD

**Issue by dmalyuta** [Sodel-the-Vociferous/helm-company#2]
Suppose I am editing a C++ source file and the code is at this state, with the cursor placed at the end of `std::stri`:
```
#include <string>
#include <iostream>

int main()
{
  std::stri
}
```
I trigger `helm-company` in order to get completion (I want to complete to `std::string`). This is what comes up:
![image](https://cloud.githubusercontent.com/assets/12475811/26766342/8e3ac758-4944-11e7-8834-6e38c89702da.png)

The "pattern" input field is empty, even though I have already typed `stri`. It would be nice if `helm-company` would already place in the input field what I typed so far, because often I find myself retyping what I had already typed in order to narrow down the completion list to what it is that I actually want.

**Comment by Sodel-the-Vociferous** [comment]
Hi @dmalyuta,

Good suggestion. :) I have added this for you, though it isn't enabled by default. Set the `helm-company-initialize-pattern-with-thing-at-point` customization variable to `t`, and you should be good to go. Let me know if this works how you want it to!

**Comment by dmalyuta** [comment]
Fantastic, thanks for the fast response. Would this be available on MELPA already, or do I need to go through `git clone` manually (I use `use-package` typically to load packages automatically)?

**Comment by Sodel-the-Vociferous** [comment]
No problem!

MELPA takes some time to update its packages, so this change won't be on MELPA yet. If you want to try it right now, you'll have to `git-clone` it, or just overwrite your copy of  `helm-company.el` with this one.

**Comment by dmalyuta** [comment]
It works, but I discovered now what seems to be a new bug (or maybe I simply did not notice it before)? Anyway, I checked and the same bug is present in the MELPA version. When I cancel a completion (`C-g` after toggling completion at point), company's original popup shows:

![helm_company_bug](https://cloud.githubusercontent.com/assets/12475811/26770711/e79569ba-496d-11e7-8deb-9d8a5507cf0c.gif)

What could be the issue here? I am on Ubuntu 14.04.5 and Emacs 25.2.1

**Comment by Sodel-the-Vociferous** [comment]
Thanks! I found the source of that glitch, and it should be fixed in the `master` branch now.

Since this seems to be working for you, I'll mark this issue as closed. :)

**Comment by dmalyuta** [comment]
This feature seems to have disappeared in the master branch? Now again the "pattern" field is not getting filled in with the partial phrase:

![gifrecord_2017-06-08_101247](https://user-images.githubusercontent.com/12475811/26941614-f641a19a-4c33-11e7-9b2c-a0bb1fc169bc.gif)

**Comment by Sodel-the-Vociferous** [comment]
Hi @dmalyuta,

I renamed the configuration variable that enables this to `helm-company-initialize-pattern-with-prefix`. I don't think I'll be renaming any more customization variables from this point on.
