### ISSUE TITLE
doc persistent action is broken

### ISSUE THREAD

**Issue by ag91** [Sodel-the-Vociferous/helm-company#23]
hello, I was trying out this mode and I could not show documentation of Elisp functions for the persistent action.

I found out that https://github.com/Sodel-the-Vociferous/helm-company/blob/master/helm-company.el#L181 is broken because display-buffer doesn't seem to take those arguments anymore.

For reference this is how I fixed it:

``` elisp
(defun helm-company-display-document-buffer (buffer)
      "Temporarily show the documentation BUFFER."
      (with-current-buffer buffer
        (goto-char (point-min)))
      (let ((display-buffer-alist '((".*" display-buffer-in-side-window)
                                    (".*" display-buffer-reuse-window))))
        (display-buffer buffer t)))
```

**Comment by Sodel-the-Vociferous** [comment]
I have incorporated your fix. Thank you for the report and solution!
