### ISSUE TITLE
Cancelling `helm-company` with C-g displays the Company completion menu again

### ISSUE THREAD

**Issue by Sodel-the-Vociferous** [Sodel-the-Vociferous/helm-company#5]
See https://github.com/Sodel-the-Vociferous/helm-company/issues/2#issuecomment-306101511

**Comment by Sodel-the-Vociferous** [comment]
Fixed in e8bb821.

**Comment by dmalyuta** [comment]
I confirm that this fixes the issue for me. Thank you!
