### ISSUE TITLE
How to show type information in helm-company?

### ISSUE THREAD

**Issue by ghost** [Sodel-the-Vociferous/helm-company#6]
Hi,

When using company-mode with C++, I see that type information can be displayed beside function names. However, for helm-company, only the function names are displayed.

So, I'd like to ask how to make helm-company display the type information as well?

Thanks!

**Comment by Sodel-the-Vociferous** [comment]
Hi @tddsg,

Funny you should mention this! I just merged this feature into the `master` branch. I don't think the MELPA package has been updated yet, but it should be in the next day or so. If you want, you can clone the `master` branch until then.

This is how helm-company will look now:

![helm-company-with-annotations](https://cloud.githubusercontent.com/assets/918813/26771807/611345e8-4976-11e7-9ed5-1c76e16e750a.png)

Let me know what you think!

**Comment by ghost** [comment]
Awesome! This is exactly what I am looking for in months!

**Comment by ghost** [comment]
I have a suggestion for the color of the type information. It seems that the orange color and the underline text take more attention than the function name. 

Could you consider some light theme like this?  https://raw.githubusercontent.com/wiki/ocaml/merlin/emacs-ac.png

**Comment by Sodel-the-Vociferous** [comment]
That's a good suggestion. I will play around with a few different font colours, and pick something less attention-grabbing.

**Comment by Sodel-the-Vociferous** [comment]
Ok, the type information should not show up in the same colour that they do in the `company` completion menu, which should be appropriate for any theme you use.

**Comment by ghost** [comment]
Great work. The color now looks very cool!

**Comment by Sodel-the-Vociferous** [comment]
Thank you!
